name: notepad
description: A simple notepad app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.3.0
  sqflite: ^2.3.2
  path: ^1.8.3
  crypto: ^3.0.3
  package_info_plus: ^4.0.2
  local_auth: ^2.1.8
  open_filex: ^4.7.0
  lecle_downloads_path_provider: ^0.0.2+8
  path_provider: ^2.1.2
  device_info_plus: ^9.0.2
  fluttertoast: ^8.2.2
  encrypt: ^5.0.3
  file_selector: ^1.0.3
  win32: ^5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
