name: notepad
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  dartz: ^0.10.1
  equatable: ^2.0.7
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  flutter_quill:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      ref: master
  flutter_quill_extensions:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      path: flutter_quill_extensions
      ref: master
  uuid: ^4.3.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  path_provider: ^2.1.2
  sqflite: ^2.4.2
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_quill:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      ref: master
